import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased bg-neutral-200 flex justify-center items-center h-screen`}
      >
        <div className="relative w-full max-w-[420px] min-w-[320px] h-full max-h-[900px] min-h-[500px] bg-black overflow-hidden">
          {children}
        </div>
      </body>
    </html>
  );
}
